{
  "success": false,
  "return_code": 1,
  "stdout": "",
  "stderr": "Traceback (most recent call last):\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v3/10_23_2025/backtests_optimized/FractalCascade_OPT_v7.py\", line 181, in <module>\n    stats = bt.run()\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 1170, in run\n    strategy.next()\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v3/10_23_2025/backtests_optimized/FractalCascade_OPT_v7.py\", line 86, in next\n    risk_amount = risk_per_trade * self._broker.get_equity()\nAttributeError: '_Broker' object has no attribute 'get_equity'. Did you mean: '_equity'?\n\nERROR conda.cli.main_run:execute(124): `conda run python /Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v3/10_23_2025/backtests_optimized/FractalCascade_OPT_v7.py` failed. (See above for error)\n",
  "execution_time": 1.427688,
  "timestamp": "2025-10-23T09:04:42.520834"
}